Flex sensor dev to master sprint 5
R2D2-2018/STRAIN_GAUGE pull request #4
Opened 2018-06-18 13:06 UTC by Michelbaartman

https://trello.com/c/XtY1TbEO/23-vs3-strain-gauge-slice
The strain gauge class has been improved for compatibility has been improved for multiple resistance returning sensors. 
A flex sensor class has been added with functionality of returning the angle of the sensor.

2018-06-19 22:38 UTC, BIGduzy reviewed
Think better about your dataTypes, don't just use int but
use uint32_t when there is no negative etc.

2018-06-19 22:38 UTC, BIGduzy commented on BuildModule.cmake
> +    src/strain_gauge.cpp
I believe these files are already in your Sources.cmake

2018-06-19 22:38 UTC, BIGduzy commented on src/strain_gauge.cpp
> + * @author    Joost van Lingen
Don't remove the old author, just add yours

2018-06-19 22:38 UTC, BIGduzy commented on src/strain_gauge.cpp
> +    for (int i = 0; i < 4; i++) {
Use the size of the array for this function, so that the function does not break when a larger array is needed in the future.

2018-06-19 22:41 UTC, BIGduzy requested changes
Fix the small mistakes, then I will merge the pull request.

2018-06-20 09:44 UTC, j00st commented on src/strain_gauge.cpp
> + * @author    Joost van Lingen
In the compare it looks like I just changed the author while I rewrote the entire file, which is why I didn't add Willem.

2018-06-22 12:38 UTC, BIGduzy requested changes
Not all changes are approved yet.

2018-06-22 12:38 UTC, BIGduzy commented on src/strain_gauge.hpp
> +    const uint32_t maxVoltage = 3300;            ///< Voltage when no resistance is applied
The max unsigned 16 bit value = 65536, so these values fit inside uint16_t.

2018-06-22 12:38 UTC, BIGduzy commented on src/strain_gauge.cpp
> + * @author    Joost van Lingen
https://github.com/R2D2-2018/STRAIN_GAUGE/blame/development/src/strain_gauge.cpp

A great deal of the file was written by @vasilishomegas, so just keep him in the author list.

2018-06-22 12:57 UTC, j00st commented on src/strain_gauge.cpp
> + * @author    Joost van Lingen
I just noticed these lines are in the source file where they shouldn't even be, I'll add both authors to the header file.

2018-06-25 15:43 UTC, BIGduzy approved these changes

2018-06-25 15:43 UTC, merged